image: edbizarro/gitlab-ci-pipeline-php:8.0-alpine

before_script:  
  # Update Composer
  - sudo composer self-update  
  
  # Install project dependencies.
  - sudo COMPOSER_MEMORY_LIMIT=-1 composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
  - vendor/

stages:
  - test
  - deploy

testing:
  only:
    - master
  stage: test
  script:
  # run tests
  - echo "Running PHPUnit Tests"
  - ./vendor/bin/phpunit 

deploy_composer:
  only:
    - tags
  stage: deploy
  script:
    - curl -sS --show-error --fail --data tag=${CI_COMMIT_TAG} "https://__token__:${DEPLOY_TOKEN}@gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/composer"
