image: composer:latest

before_script:  
  # Update Composer
  - composer self-update  
  
  # Install project dependencies.
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
  - vendor/

stages:
  - test
  - tag
  - deploy

testing:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  stage: test
  script:
  # run tests
  - echo "Running PHPUnit Tests"
  - ./vendor/bin/phpunit 

tag_release:
  stage: tag
  only:
    - master
  script:
    - VERSION="$(php -r "echo json_decode(file_get_contents('./composer.json'), true)['version'];")";
    - MESSAGE="$(php -r "echo json_encode(['name' => 'Version $VERSION', 'tag_name' => '$VERSION', 'description' => file_get_contents('./changelog/$VERSION.md')]);")";
    - git config --global user.email "your_email"
    - git config --global user.name "username"
    - git remote add api-origin https://oauth2:${OAUTH2_TOKEN}@gitlab.com/altra_airzone/altra-context
    - >
      if [ $(git tag -l "$VERSION") ]; then
        echo "Version $VERSION already exists"
      else
        git tag -a $VERSION -m "Version $VERSION"
        git push api-origin $VERSION
        curl --header 'Content-Type: application/json' --header "PRIVATE-TOKEN: $OAUTH2_TOKEN" \
           --data "$MESSAGE" \
           --request POST https://gitlab.com/api/v4/projects/altra_airzone/altra-context/releases
      fi

deploy_composer:
  only:
    - tags
  stage: deploy
  script:
    - curl -sS --show-error --fail --data tag=${CI_COMMIT_TAG} "https://__token__:${DEPLOY_TOKEN}@gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/composer"
